variables:

  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    --no-snapshot-updates
    -DinstallAtEnd=true
    -DdeployAtEnd=true

default:
  image: maven:3.9.11-eclipse-temurin-21
  cache:
    - key: m2_cache
      paths:
        - .m2/repository
    - key: npm_cache
      paths:
        - frontend/node/
        - frontend/node_modules/

stages:
  - build
  - test

build:backend:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -pl backend compile
  artifacts:
    paths:
      - backend/target/
    expire_in: 1 hour

build:frontend:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -pl frontend compile
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour

test:backend:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -pl backend test
  artifacts:
    when: always
    reports:
      junit:
        - backend/target/surefire-reports/TEST-*.xml

test:frontend:
  stage: test
  before_script:
    - apt-get update -y
    # Install native libraries required by Chromium used by Puppeteer
    - apt-get install -y --no-install-recommends \
      ca-certificates \
      libnss3 \
      libxss1 \
      libasound2t64 \
      libatk1.0-0t64 \
      libatk-bridge2.0-0t64 \
      libgtk-3-0t64 \
      libgbm1 \
      libxshmfence1 \
      fonts-liberation
  script:
    - mvn $MAVEN_CLI_OPTS -pl frontend test
