variables:

  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    --no-snapshot-updates
    -DinstallAtEnd=true
    -DdeployAtEnd=true

default:
  image: maven:3.9.11-eclipse-temurin-21
  cache:
    - key: m2_cache
      paths:
        - .m2/repository
    - key: npm_cache
      paths:
        - frontend/node/
        - frontend/node_modules/

stages:
  - build
  - test

build:backend:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -pl backend compile
  artifacts:
    paths:
      - backend/target/
    expire_in: 1 hour

build:frontend:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -pl frontend compile
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour

test:backend:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -pl backend test
  artifacts:
    when: always
    reports:
      junit:
        - backend/target/surefire-reports/TEST-*.xml

test:frontend:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y chromium
    - export CHROME_BIN=$(command -v chromium)
    - export CHROME_FLAGS="--no-sandbox --disable-gpu --disable-dev-shm-usage"
  script:
    - mvn $MAVEN_CLI_OPTS -pl frontend test
